// require('./any-series');
// require('./any');
// require('./each-right--series');
// require('./each-right');
// require('./each-series');
// require('./each');
// require('./every-series');
// require('./every');
// require('./filter-series');
// require('./filter');
// require('./map-series');
// require('./map');
// require('./pack');
// require('./packs');
// require('./parallel');
// require('./reduce-right-series');
// require('./reduce-right');
require('./reduce-series');
require('./reduce');
// require('./reject-series');
// require('./reject');
require('./sequence');
// require('./series');
// require('./some-series');
// require('./some');
// require('./throws');
// require('./unpack');
